version: '3.3'
services:
  sd_gg:
    container_name: sd_gg
    image: soda/sd_gg:0.0.1
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    env_file:
      - ./.env
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "3"
    # command: sleep infinity
